name: Build Edge Docker Image

# Edge Docker images are built for every commit, and daily
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - LICENSE.txt
  schedule:
    - cron: '0 0 * * *'

env:
  IMAGES: |
    jlongster/actual-server
    ghcr.io/actualbudget/actual-server

  # Creates the following tags:
  # - actual-server:edge
  TAGS: |
    type=edge,value=edge

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # Push to both Docker Hub and Github Container Registry
          images: ${{ env.IMAGES }}
          tags: ${{ env.TAGS }}

      - name: Docker meta for Alpine image
        id: alpine-meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGES }}
          flavor: suffix=-alpine
          tags: $${{ env.TAGS }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push standard image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: docker/edge-ubuntu.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}

      - name: Build and push Alpine image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: docker/edge-alpine.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.alpine-meta.outputs.tags }}
