name: Release Docs to Github Pages

# Release docs on every push to master
on:
  push:
    branches:
      - master
    paths:
      - "packages/docs/**"
      - ".github/workflows/docs-spelling.yml"
      - ".github/actions/docs-spelling/**"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Docs
    steps:
      - name: Docusaurus Deploy
        run: |
          GIT_USER=MikesGlitch \
          GIT_PASS=${{ secrets.DOCS_GITHUB_PAGES_DEPLOY }} \
          GIT_USER_NAME=github-actions[bot] \
          GIT_USER_EMAIL=github-actions[bot]@users.noreply.github.com \
          yarn deploy:docs
