name: E2E Tests

on:
  pull_request:
    paths:
      - "packages/**"
      - ".github/workflows/e2e-test.yml"
      - "!packages/sync-server/**" # Sync server changes don't affect E2E tests
      - "!packages/api/**" # API changes don't affect E2E tests
      - "!packages/ci-actions/**" # CI actions changes don't affect E2E tests
      - "!packages/docs/**" # Docs changes don't affect E2E tests
      - "!packages/eslint-plugin-actual/**" # Eslint plugin changes don't affect E2E tests

env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  netlify:
    name: Wait for Netlify build to finish
    runs-on: ubuntu-latest
    outputs:
      netlify_url: ${{ steps.netlify.outputs.url }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Wait for Netlify build to finish
        id: netlify
        env:
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/actions/netlify-wait-for-build

  functional:
    name: Functional
    needs: netlify
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.0-jammy
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Trust the repository directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Run E2E Tests on Netlify URL
        run: yarn e2e
        env:
          E2E_START_URL: ${{ needs.netlify.outputs.netlify_url }}
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: always()
        with:
          name: desktop-client-test-results
          path: packages/desktop-client/test-results/
          retention-days: 30
          overwrite: true

  functional-desktop-app:
    name: Functional Desktop App
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.0-jammy
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Trust the repository directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Run Desktop app E2E Tests
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" -- yarn e2e:desktop
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: always()
        with:
          name: desktop-app-test-results
          path: packages/desktop-electron/e2e/test-results/
          retention-days: 30
          overwrite: true

  vrt:
    name: Visual regression
    needs: netlify
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.0-jammy
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Run VRT Tests on Netlify URL
        run: yarn vrt
        env:
          E2E_START_URL: ${{ needs.netlify.outputs.netlify_url }}
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: always()
        with:
          name: desktop-client-test-results
          path: packages/desktop-client/test-results/
          retention-days: 30
          overwrite: true
