name: Generate release PR

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Commit or branch to release'
        required: true
        default: 'master'
      version:
        description: 'Version number for the release (optional)'
        required: false
        default: ''

jobs:
  generate-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Bump package versions
        id: bump_package_versions
        shell: bash
        run: |
          declare -A packages=(
            [web]="desktop-client"
            [electron]="desktop-electron"
            [sync]="sync-server"
            [api]="api"
          )

          for key in "${!packages[@]}"; do
            pkg="${packages[$key]}"

            if [[ -n "${{ github.event.inputs.version }}" ]]; then
              version="${{ github.event.inputs.version }}"
            else
              version=$(node ./.github/actions/get-next-package-version.js \
                --package-json "./packages/$pkg/package.json" \
                --type auto \
                --update)
            fi

            eval "NEW_${key^^}_VERSION=\"$version\""
          done

          echo "version=$NEW_WEB_VERSION" >> "$GITHUB_OUTPUT"
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'ğŸ”– (${{ steps.bump_package_versions.outputs.version }})'
          title: 'ğŸ”– (${{ steps.bump_package_versions.outputs.version }})'
          body: 'Generated by [generate-release-pr.yml](../tree/master/.github/workflows/generate-release-pr.yml)'
          branch: 'release/v${{ steps.bump_package_versions.outputs.version }}'
