name: Package Server

defaults:
  run:
    shell: bash

env:
  CI: true

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  package-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build the server
        run: yarn build:server
      - name: Upload Server with Client Build
        uses: actions/upload-artifact@v4
        with:
          name: sync-server
          include-hidden-files: true
          path: |
            package.json
            yarn.lock
            .yarn
            .yarnrc.yml
            packages/sync-server/package.json
            packages/sync-server/app.js
            packages/sync-server/src
            packages/sync-server/migrations
            packages/sync-server/web-client
      - name: Download Server with Client Build
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/download-artifact@v4
        with:
          name: sync-server
          path: sync-server
      - name: Zip Server with Client Build
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd sync-server
          zip -r ../sync-server.zip .
      - name: Add to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: sync-server.zip
