name: Publish Edge npm packages

# Edge npm packages are built daily
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-pack:
    runs-on: ubuntu-latest
    name: Build and pack npm packages
    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Update package versions
        run: |
          # e.g. 25.6.0-edge.23 if todays date is 2025-05-23
          # e.g. 26.1.0-edge.12 if todays date is 2025-12-12
          EDGE_VERSION=$(date -d "+1 month" +%y.%-m.0-edge.%-d)
          npm version $EDGE_VERSION --no-git-tag-version --workspace=@actual-app/web --no-workspaces-update
          npm version $EDGE_VERSION --no-git-tag-version --workspace=@actual-app/sync-server --no-workspaces-update
          npm version $EDGE_VERSION --no-git-tag-version --workspace=@actual-app/api --no-workspaces-update

      - name: Yarn install
        run: |
          yarn install

      - name: Build Web
        run: yarn build:server

      - name: Pack the web and server packages
        run: |
          yarn workspace @actual-app/web pack --filename @actual-app/web.tgz
          yarn workspace @actual-app/sync-server pack --filename @actual-app/sync-server.tgz

      - name: Build API
        run: yarn build:api

      - name: Pack the api package
        run: |
          yarn workspace @actual-app/api pack --filename @actual-app/api.tgz

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: npm-packages
          path: |
            packages/desktop-client/@actual-app/web.tgz
            packages/sync-server/@actual-app/sync-server.tgz
            packages/api/@actual-app/api.tgz

  publish:
    runs-on: ubuntu-latest
    name: Publish Edge npm packages
    needs: build-and-pack
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download the artifacts
        uses: actions/download-artifact@v4
        with:
          name: npm-packages

      - name: Setup node and npm registry
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Publish Web
        run: |
          npm publish desktop-client/@actual-app/web.tgz --access public --tag edge
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Sync-Server
        run: |
          npm publish sync-server/@actual-app/sync-server.tgz --access public --tag edge
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish API
        run: |
          npm publish api/@actual-app/api.tgz --access public --tag edge
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
